abstract final class AurumRoutes {
  static const splash = '/splash';
  static const onboarding = '/onboarding';
  static const login = '/login';
  static const register = '/register';
  static const forgotPassword = '/forgot-password';
  static const home = '/home';
  static const markets = '/markets';
  static const analysis = '/analysis';
  static const aiAnalysis = '/ai-analysis';
  static const portfolio = '/portfolio';
  static const journal = '/journal';
  static const scanner = '/scanner';
  static const profile = '/profile';
  static const asset = '/asset';
  static const watchlist = '/watchlist';
  static const notifications = '/notifications';
  static const alerts = '/alerts';
}
